import { Scene } from '@/core/types'

export const sceneSeed: Scene[] = [
  {
    id: 'scene_caminho_predio',
    title: 'Caminho até o prédio principal',
    content: 'Você cruza o pátio e encontra alguns colegas se arrumando para o primeiro dia.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: {
      energy: { min: 0, max: 0 },
      items: null,
      reputation: null,
    },
  },
  {
    id: 'scene_primeira_aula',
    title: 'Primeira aula do dia',
    content: 'Uma explicação introdutória sobre a Academia e seus objetivos.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: { reputation: [{ stock: 0 }], items: null, energy: { min: null, max: null } },
  },
  {
    id: 'scene_treino_basico',
    title: 'Treino de habilidades',
    content: 'Um exercício prático para despertar sua magia interior.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: { energy: { min: null, max: null }, items: null, reputation: null },
  },
  {
    id: 'scene_encontro_noturno',
    title: 'Encontro no pátio ao anoitecer',
    content: 'Conversas baixas, promessas de aventuras e segredos sussurrados.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: {
      items: [{ item_notebook: 1 }],
      energy: { min: null, max: null },
      reputation: null,
    },
  },
  {
    id: 'scene_manha_aula',
    title: 'Aula de Alquimia',
    content: 'Você entra no laboratório e o cheiro de ervas toma o ar.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: { energy: { min: null, max: null }, items: null, reputation: null },
  },
  {
    id: 'scene_tarde_treino',
    title: 'Treino no Pátio',
    content: 'O sol das duas da tarde castiga enquanto você pratica.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: { energy: { min: null, max: null }, items: null, reputation: null },
  },
  {
    id: 'scene_noite_social',
    title: 'Clube de Estratégia',
    content: 'Um grupo se reúne para jogos táticos no salão.',
    options: [],
    cost: null,
    hours: null,
    weekdays: null,
    preRequire: { energy: { min: null, max: null }, items: null, reputation: null },
  },
]
