import { ANIMAL_ENUM, RACE_ENUM, STAT_TYPE } from '@/domain/constants'
import { StatsBase } from '@/infra/schemas'

export const statsBaseSeed: StatsBase[] = [
  // Base de raças
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.arcane,
    agility: 1,
    charisma: 0,
    intelligence: 3,
    stamina: 0,
    strength: 0,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.banshee,
    agility: 1,
    charisma: 3,
    intelligence: 1,
    stamina: 0,
    strength: 0,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.kanime,
    agility: 3,
    charisma: 0,
    intelligence: 1,
    stamina: 2,
    strength: 2,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.kitsune,
    agility: 2,
    charisma: 2,
    intelligence: 2,
    stamina: 1,
    strength: 1,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.werewolf,
    agility: 2,
    charisma: 1,
    intelligence: 0,
    stamina: 3,
    strength: 3,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.vampire,
    agility: 2,
    charisma: 2,
    intelligence: 1,
    stamina: 2,
    strength: 2,
  },
  {
    type: STAT_TYPE.race,
    target: RACE_ENUM.wiccan,
    agility: 0,
    charisma: 1,
    intelligence: 3,
    stamina: 1,
    strength: 0,
  },

  // Base de animais
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.wolf,
    agility: 3,
    charisma: 1,
    intelligence: 2,
    stamina: 3,
    strength: 2,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.bear,
    agility: 1,
    charisma: 1,
    intelligence: 2,
    stamina: 3,
    strength: 3,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.lion,
    agility: 2,
    charisma: 2,
    intelligence: 2,
    stamina: 2,
    strength: 3,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.tiger,
    agility: 3,
    charisma: 1,
    intelligence: 2,
    stamina: 2,
    strength: 3,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.eagle,
    agility: 3,
    charisma: 2,
    intelligence: 2,
    stamina: 2,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.hawk,
    agility: 3,
    charisma: 1,
    intelligence: 2,
    stamina: 2,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.owl,
    agility: 2,
    charisma: 2,
    intelligence: 2,
    stamina: 2,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.snake,
    agility: 2,
    charisma: 1,
    intelligence: 1,
    stamina: 3,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.horse,
    agility: 2,
    charisma: 2,
    intelligence: 1,
    stamina: 3,
    strength: 3,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.fox,
    agility: 3,
    charisma: 2,
    intelligence: 3,
    stamina: 2,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.dog,
    agility: 2,
    charisma: 3,
    intelligence: 2,
    stamina: 3,
    strength: 1,
  },
  {
    type: STAT_TYPE.animal,
    target: ANIMAL_ENUM.cat,
    agility: 3,
    charisma: 2,
    intelligence: 2,
    stamina: 2,
    strength: 1,
  },
]

// TODO criar helper para pegar animal aleatório:  buscar stats base por 'animal' e depois escolher um aleatório

// TODO criar um helper para pegar os stats da raça (se transformo pega animal aleatório | se kitsune pega animal fixo)

// TODO implementar stats base:
/*
  hungry: 50,
  mood: 50,
  health: 100,

  magic: 0,
  mana: 0,
 */
